name: Deploy Code on Server

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy-test-server:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy test.txt file to main server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          pass: Ubuntu@123
          user: ubuntu
          host: 43.231.127.206
          scp: |
            ./test => /home/ubuntu
